# YOUR PROJECT TITLE

> **Note the following:** 
> 1. This is *not* meant to be an example of an actual **data analysis project**, just an example of how to structure such a project.
> 1. Remember the general advice on structuring and commenting your code
> 1. The `dataproject.py` file includes a function which can be used multiple times in this notebook.

Imports and set magics:

In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import ipywidgets as widgets
#from matplotlib_venn import venn2

# autoreload modules when code is run
%load_ext autoreload
%autoreload 2

# user written modules
import dataproject

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [21]:
gdp = dataproject.gdp
pop = dataproject.population
gdp.describe(include="")

,unit,na_item,Country_code,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
count,38,38,38,3.800000e+01,3.800000e+01,3.800000e+01,3.800000e+01,3.800000e+01,3.800000e+01,3.800000e+01,3.800000e+01,3.700000e+01,3.600000e+01,3.500000e+01
unique,1,1,38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,CLV15_MEUR,B1GQ,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,38,38,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,4.177853e+05,4.208153e+05,4.291235e+05,4.396628e+05,4.484415e+05,4.610989e+05,4.703213e+05,4.781218e+05,3.945065e+05,4.283899e+05,4.258100e+05
std,NaN,NaN,NaN,7.075664e+05,7.125254e+05,7.261159e+05,7.381322e+05,7.514748e+05,7.685381e+05,7.781122e+05,7.876217e+05,6.554578e+05,6.918891e+05,7.113397e+05
min,NaN,NaN,NaN,3.353700e+03,3.472700e+03,3.534700e+03,3.654500e+03,3.762300e+03,3.939700e+03,4.139800e+03,4.308000e+03,3.648600e+03,4.124500e+03,4.375800e+03
25%,NaN,NaN,NaN,2.560155e+04,2.624722e+04,2.651638e+04,2.736412e+04,2.809895e+04,2.891793e+04,3.011967e+04,3.106728e+04,2.710860e+04,3.991457e+04,3.678510e+04
50%,NaN,NaN,NaN,1.531142e+05,1.532790e+05,1.581330e+05,1.649230e+05,1.693643e+05,1.779040e+05,1.845607e+05,1.891194e+05,1.672377e+05,1.858119e+05,1.920673e+05
75%,NaN,NaN,NaN,3.984359e+05,4.006563e+05,4.109299e+05,4.265513e+05,4.373923e+05,4.561604e+05,4.737487e+05,4.834362e+05,4.223568e+05,4.639938e+05,4.570067e+05
max,NaN,NaN,NaN,2.904528e+06,2.917238e+06,2.981695e+06,3.026180e+06,3.093664e+06,3.176581e+06,3.207751e+06,3.241644e+06,3.121807e+06,3.203817e+06,3.261012e+06